# Site settings
title: Yet another coder
email: anti2moron@gmail.com
description: >
  AntiMoron's blog. AntiMoron is just a normal guy who knows how to program.
# For more info about the author just check this page.
baseurl: ""
url: "http://antimoron.github.io"
github_username: antimoron
facebook_username: boyuan.gao.7
# Build settings
markdown: kramdown
